project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  title: 'Reproducible Research with <img style="vertical-align:middle; height:1em; border: none; background: none;" src="assets/images/Rlogo.png"> and <img style="vertical-align:middle; height:1em;" src="assets/images/quarto-logo-trademark.svg">'
  search: TRUE #add search bar
  site-url: "https://blenback.github.io/R-for-Reproducible-Research/"
  description: "Website for workshop in reproducible research with R and Quarto"
  twitter-card:
    image: "media/preview.png"
    card-style: "summary_large_image"
    creator: "@Blen_Back"
    site: "@Blen_Back"
  open-graph: true
  google-analytics:
    tracking-id: "G-9CCC34ZV10"
    anonymize-ip: true
  page-footer:
    left: |
      {{< fa regular copyright >}} Benjamin Black, 2024<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
  navbar:
    alignment: "center"
    background: secondary
    foreground: light
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/blenback/R-for-Reproducible-Research
          - text: Report a Bug
            url:  https://github.com/blenback/R-for-Reproducible-Research/issues
  sidebar:
    alignment: "left"
    style: "docked"
    border: false
    search: true
    contents:
      - text: "View in presentation format"
        icon: "bi-file-earmark-easel"
        href: presentation.html
    collapse-level: 1
  
format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    #clean.scss
    #css: css/styles.css
    page-layout: article
    grid:
      sidebar-width: 350px
      body-width: 1100px
      margin-width: 50px
      gutter-width: 1.5rem
crossref:
  fig-title: ''
  fig-labels: none
bibliography: references.bib
csl: diabetologia.csl
execute:
  echo: false
  error: true
  warning: false

